name: kaarte_app
description: Kaart Flutter project mobile.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:

  share: ^2.0.4
  package_info: ^2.0.2
  url_launcher: ^6.0.7
  http: ^0.13.3
  connectivity: ^3.0.6
  lottie: ^1.0.1
  bot_toast: ^4.0.1
  retrofit_generator: ^2.0.0+1
  retrofit: ^2.0.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  get: ^4.1.4
  google_fonts: any
  dio: ^4.0.0
  firebase_core: ^1.3.0
  firebase_analytics: ^8.2.0
  firebase_crashlytics: ^2.0.6
  firebase_storage: ^10.0.2
  firebase_auth: ^3.0.2
  cloud_firestore: ^2.5.0
  flutter_launcher_icons: ^0.9.0
  fluentui_system_icons: ^1.1.132
  flutter_statusbarcolor_ns: ^0.3.0-nullsafety
  screenshot: ^1.2.3
  flutter_spinkit: ^5.0.0
  brasil_fields: ^1.1.4
  image_picker: ^0.8.3+3
  image_cropper: ^1.4.1
  cached_network_image: ^3.1.0
  flutter_cache_manager: ^3.1.2
  shimmer: ^2.0.0
  intl: ^0.17.0
  path_provider: ^1.6.11
  share_plus: ^3.0.2
  flutter:
    sdk: flutter


dev_dependencies:
  hive_generator: ^1.1.0
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
      #- assets/icons/
      - assets/images/
      #- assets/animation/

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon_laucher_android.png"
  image_path_ios: "assets/icons/icon_laucher_ios.png"